name: wordle
description: Wordle
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  fluent_ui: ^3.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutterfire_ui: ^0.3.5+1
  freezed_annotation: ^1.1.0
  google_fonts: ^2.3.1
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  lint: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/dictionary.txt