name: wordly
description: Guess the WORD in six tries
publish_to: none
version: 2.2.2+24
environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  bloc: ^8.1.2
  collection: any
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  intl: any
  json_annotation: ^4.8.1
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.6
  carapacik_lints: ^1.5.1
  flutter_native_splash: ^2.3.2
  freezed: ^2.4.3
  icons_launcher: ^2.1.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - google_fonts/

flutter_intl:
  enabled: true
  class_name: R
  main_locale: en
  output_dir: lib/resources/
  arb_dir: assets/l10n/

flutter_native_splash:
  color: '#F4FFFF'
  image: assets/images/splash_light.png
  color_dark: '#0D1117'
  image_dark: assets/images/splash_dark.png
  android: true
  ios: true
  web: true
  fullscreen: true

icons_launcher:
  image_path: assets/images/ic_logo_border.png
  platforms:
    android:
      enable: true
      adaptive_background_image: assets/images/ic_background.png
      adaptive_foreground_image: assets/images/ic_foreground.png
      adaptive_round_image: assets/images/ic_foreground.png
    ios:
      enable: true
      image_path: assets/images/ic_logo.png
    web:
      enable: true
      image_path: assets/images/ic_logo_transparent.png
      favicon_path: assets/images/ic_logo_transparent.png
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
