name: wordly
description: Guess the WORD in six tries
publish_to: none
version: 1.0.3+4
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  another_flushbar: ^1.10.28
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  in_app_review: ^2.0.4
  in_app_update: ^3.0.0
  isar: ^2.2.1
  isar_flutter_libs: 2.2.1
  path_provider: ^2.0.9
  r_resources: ^1.0.1
  share_plus: ^4.0.3
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.8
#  flutter_launcher_icons_maker: ^0.10.2
#  flutter_native_splash: ^2.1.2+1
  flutter_test:
    sdk: flutter
  isar_generator: 2.2.1
  lint: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/strings/
    - assets/svg/
    - google_fonts/

#flutter_icons:
#  android: true
#  ios: true
#  web: true
#  windows: true
#  image_path: assets/images/icon.png

#flutter_native_splash:
#  color: '#F4F7FB'
#  image: assets/images/splash_light.png
#  color_dark: '#1E1F30'
#  image_dark: assets/images/splash_dark.png
#  android: true
#  ios: true
#  web: true
#  fullscreen: true
