name: wordly
description: Guess the WORD in six tries
publish_to: 'none'
version: 1.2.0+12
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  bloc: ^8.0.3
  collection: ^1.16.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  in_app_review: ^2.0.4
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  path_provider: ^2.0.11
  r_resources: ^1.0.1
  share_plus: ^4.0.7
  url_launcher: ^6.1.3
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.11
  carapacik_lints:
    git:
      url: https://github.com/Carapacik/carapacik_lints.git
  flutter_native_splash: ^2.2.3
  icons_launcher: ^1.2.1
  isar_generator: ^2.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/strings/
    - assets/svg/
    - google_fonts/

flutter_icons:
  image_path: 'assets/ic_logo.png'
  adaptive_icon_background: 'assets/ic_background.png'
  adaptive_icon_foreground: 'assets/ic_foreground.png'
  remove_alpha_ios: false
  remove_alpha_macos: false
  android: true
  ios: true
  linux: true
  macos: true
  web: true
  windows: true

flutter_native_splash:
  color: '#F4F7FB'
  image: assets/splash_light.png
  color_dark: '#1E1F30'
  image_dark: assets/splash_dark.png
  android: true
  ios: true
  linux: true
  macos: true
  web: true
  windows: true
  fullscreen: true