name: analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Run analyze"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Code generation
        run: flutter pub run build_runner build -d
      - name: Analyze
        run: flutter analyze
