name: github pages

on:
  push:
    branches:
      - main

jobs:
  pages:
    name: "Deploy on Github Pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Code generation
        run: flutter pub run build_runner build -d
      - name: Build
        run: flutter build web
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: ./build/web
